### ISSUE TITLE
Bug with reverse proxy 

### ISSUE THREAD

**Issue by k33g** [bots-garden/capsule#79]
```
2022/08/09 06:29:37 http: panic serving [::1]:46346: interface conversion: interface {} is []string, not []interface {}
goroutine 13 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0xa3fc80, 0xc000482540})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/bots-garden/capsule/capsulelauncher/services/reverse-proxy.proxy(0xc000232f00)
        /github/workspace/capsulelauncher/services/reverse-proxy/main.go:64 +0x213
```

**Comment by k33g** [comment]
And allow to use it without the config file

**Comment by k33g** [comment]
done with release 0.1.1
